source :rubygems
gem "diff-lcs", "~>1.1.2"
gem "cucumber", "~>1.2.1"

gem "selenium-webdriver", "~> 2.30.0"
gem "rspec", "~>2.6.0"
gem "selenium-client", "~> 1.2.18"
gem "capybara", "~> 1.1.2"
gem "yard", "~>0.8.1"
gem "yard-cucumber", "~> 2.1.7"
gem "viewcumber", "~>0.3.1"
gem "rake", "~>0.9.2.2"
gem "logger"
gem "syntax", "~> 1.0.0"
gem "show_me_the_cookies"
gem "active_support", "~> 3.0.0"
gem "addressable","~>2.3.2"
gem "bigdecimal", "~>1.1.0"
gem "builder"
gem "bundle","~>0.0.1"
gem "bundler"
gem "i18n","~>0.6.4"
gem "io-console","~>0.3"
gem "jeweler","~>1.8.4"
gem "minitest"
gem "roo"
gem "spreadsheet"
gem "test-unit","~>2.5.3"
gem "writeexcel","~>0.6.19"
gem "yml_reader","~>0.2"